$pngBytes = [System.IO.File]::ReadAllBytes('d:\Antigravity\Test\NotiFlow\NotiFlow Icon.png')
$fs = New-Object IO.FileStream('d:\Antigravity\Test\NotiFlow\NotiFlow Icon.ico', [IO.FileMode]::Create)
$bw = New-Object IO.BinaryWriter($fs)
$bw.Write([int16]0)
$bw.Write([int16]1)
$bw.Write([int16]1)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([int16]1)
$bw.Write([int16]32)
$bw.Write([int]$pngBytes.Length)
$bw.Write([int]22)
$bw.Write($pngBytes)
$bw.Close()
$fs.Close()
